[package]
name = "govinfo"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
ureq = { version = "2.9.6", features = ["json"] }
url = "2.5.0"
chrono = { version = "0.4.34", features = ["alloc", "serde"] }
